spring:
  jpa:
    database: H2
  datasource:
    url: jdbc:h2:~/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
